#!/usr/bin/env python
"""ログ契約から OpenSearch の mapping と Collector（Fluent Bit Lua）の型表を生成する。

ADR-0040 §2。

    python scripts/gen_log_mapping.py          # 生成物を書き出す
    python scripts/gen_log_mapping.py --check  # 生成物が契約と食い違っていれば非0で終了

唯一の宣言元は ``contracts/log_contract.py``。ここは写像の規則だけを持つ。生成物は commit し、
``tests/contract/test_log_contract_mapping.py`` が drift を検査する（手で直さない）。

写像の規則（ADR-0040 §4、実測: OpenSearch 3.8.0）:

- ``dynamic: false``（未知のキーは ``_source`` に残るが index しない）
- 数値・日付は ``ignore_malformed: true``（``_ignored`` で検出できる）。
  ただし ``@timestamp`` は付けない
  （欠けると Dashboards の時間軸から見えなくなるので、Collector が不正値を置き換える）
- boolean・keyword・text は ``ignore_malformed`` 非対応（template が 400 で拒否）。型の合わない値は
  Collector の Lua が ``attributes.collector_moved`` へ退避する
- keyword は ``ignore_above: KEYWORD_MAX_CHARS``
- ``attributes`` は ``enabled: false`` の object（検索対象外）
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from contracts.log_contract import (  # noqa: E402
    APP_LOG_LABEL,
    APP_LOG_LABEL_VALUE,
    INFRA_FIELD_NAMES,
    KEYWORD_MAX_CHARS,
    LOG_FIELDS,
    LOG_SCHEMA_VERSION,
    REDACTED,
    UNKNOWN,
    UNSTRUCTURED_LINE_MAX_BYTES,
    FieldOrigin,
    FieldType,
    LogField,
    LogSource,
)

APP_MAPPING_PATH = ROOT / "deploy/logging/opensearch/templates/avp-app-mappings.json"
INFRA_MAPPING_PATH = ROOT / "deploy/logging/opensearch/templates/avp-infra-mappings.json"
LUA_TYPES_PATH = ROOT / "deploy/logging/fluent-bit/lua/contract_types.lua"

#: 時間軸に使うフィールド（ignore_malformed にしない）
TIME_FIELD = "@timestamp"

_NUMERIC_OR_DATE = {FieldType.DATE, FieldType.INTEGER, FieldType.LONG, FieldType.DOUBLE}

GENERATED_NOTE = (
    "GENERATED by scripts/gen_log_mapping.py from contracts/log_contract.py. Do not edit by hand."
)


def field_mapping(field: LogField) -> dict[str, Any]:
    """1フィールドの OpenSearch mapping。"""
    t = field.type
    if t is FieldType.OPAQUE_OBJECT:
        return {"type": "object", "enabled": False}
    if t is FieldType.KEYWORD:
        return {"type": "keyword", "ignore_above": KEYWORD_MAX_CHARS}
    if t is FieldType.TEXT:
        return {"type": "text"}
    if t is FieldType.BOOLEAN:
        return {"type": "boolean"}
    if t in _NUMERIC_OR_DATE:
        out: dict[str, Any] = {"type": t.value}
        if field.name != TIME_FIELD:
            out["ignore_malformed"] = True
        return out
    raise ValueError(f"未対応の FieldType: {t!r}")  # pragma: no cover - 新しい型を足したら落とす


def infra_fields() -> tuple[LogField, ...]:
    # 集合は契約が持つ（contracts.log_contract.INFRA_FIELD_NAMES）。順序は LOG_FIELDS に揃える
    return tuple(f for f in LOG_FIELDS if f.name in INFRA_FIELD_NAMES)


def _component(fields: tuple[LogField, ...], series: str) -> dict[str, Any]:
    return {
        "_meta": {
            "generated": GENERATED_NOTE,
            "schema_version": LOG_SCHEMA_VERSION,
            "series": series,
        },
        "template": {
            "mappings": {
                "dynamic": False,
                "properties": {f.name: field_mapping(f) for f in fields},
            }
        },
    }


def render_app_mapping() -> str:
    return json.dumps(_component(LOG_FIELDS, "app"), indent=2, ensure_ascii=False) + "\n"


def render_infra_mapping() -> str:
    return json.dumps(_component(infra_fields(), "infra"), indent=2, ensure_ascii=False) + "\n"


def _lua_str(value: str) -> str:
    # 契約の値は ASCII の識別子だけ。念のため JSON と同じ escape を使う（Lua の文字列と互換）
    return json.dumps(value, ensure_ascii=True)


def render_lua_types() -> str:
    lines = [
        f"-- {GENERATED_NOTE}",
        "-- Collector（avp_collector.lua）が型検査に使う表。値は OpenSearch の mapping 型。",
        "return {",
        f"  schema_version = {LOG_SCHEMA_VERSION},",
        f"  keyword_max_chars = {KEYWORD_MAX_CHARS},",
        f"  unstructured_line_max_bytes = {UNSTRUCTURED_LINE_MAX_BYTES},",
        f"  app_label = {_lua_str(APP_LOG_LABEL)},",
        f"  app_label_value = {_lua_str(APP_LOG_LABEL_VALUE)},",
        f"  unknown = {_lua_str(UNKNOWN)},",
        f"  redacted = {_lua_str(REDACTED)},",
        f"  time_field = {_lua_str(TIME_FIELD)},",
        "  log_source = {",
        f"    app_json = {_lua_str(LogSource.APP_JSON.value)},",
        f"    unstructured = {_lua_str(LogSource.UNSTRUCTURED.value)},",
        "  },",
        "  fields = {",
    ]
    for f in LOG_FIELDS:
        lines.append(f"    [{_lua_str(f.name)}] = {_lua_str(f.type.value)},")
    lines.append("  },")
    lines.append("  collector_fields = {")
    for f in LOG_FIELDS:
        if f.origin is FieldOrigin.COLLECTOR:
            lines.append(f"    [{_lua_str(f.name)}] = true,")
    lines.append("  },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def outputs() -> dict[pathlib.Path, str]:
    return {
        APP_MAPPING_PATH: render_app_mapping(),
        INFRA_MAPPING_PATH: render_infra_mapping(),
        LUA_TYPES_PATH: render_lua_types(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="書き出さずに drift を検査する")
    args = parser.parse_args(argv)
    drift: list[str] = []
    for path, content in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if drift:
        print("生成物が contracts/log_contract.py と食い違っている: " + ", ".join(drift))
        print("python scripts/gen_log_mapping.py で再生成すること")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
